name: Appium Tests

on: [push]

jobs:
  appium-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust to your requirements file name
      
    - name: Start Appium Server
      run: |
        npm install -g appium
        appium &
      
    - name: Run Appium Tests
      run: |
        pytest tests/  # Adjust to your test directory
      
    - name: Stop Appium Server
      run: |
        pkill -f appium
