name: Lint and Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      env:
          API_KEY: ${{ secrets.API_KEY }}
      run: | 
        pytest --junit-xml=test-results.xml
        
    - name: Run Pylint on the entire project
      run: pylint $(git ls-files '*.py')
      env:
        PYLINTRC: dev
